#!/bin/bash

echo -en "\033[1B"

while true; do
 echo -n '|'
 echo -en "\033[1D"
 sleep 1
 echo -n '/'
 echo -en "\033[1D"
 sleep 1
 echo -n '-'
 echo -en "\033[1D"
 sleep 1
 echo -n '\'
 echo -en "\033[1D"
 sleep 1
done
